// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd5MOW1DJOJ0uNpVGqyy0waoa1jD6zgcA',
    appId: '1:613181708633:web:fbfdef7c2dadc6f5cfd448',
    messagingSenderId: '613181708633',
    projectId: 'flutter-project-2aa41',
    authDomain: 'flutter-project-2aa41.firebaseapp.com',
    storageBucket: 'flutter-project-2aa41.appspot.com',
    measurementId: 'G-ZDY0P7VDNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlCfrdip0-ZpSP8e06dvJiunrUcyHI_M0',
    appId: '1:613181708633:android:b71f2ca70240b292cfd448',
    messagingSenderId: '613181708633',
    projectId: 'flutter-project-2aa41',
    storageBucket: 'flutter-project-2aa41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh70C6Yj9muY9kzMj4AtLvgbMroimuK1k',
    appId: '1:613181708633:ios:175de7fa6d8edd34cfd448',
    messagingSenderId: '613181708633',
    projectId: 'flutter-project-2aa41',
    storageBucket: 'flutter-project-2aa41.appspot.com',
    iosBundleId: 'come.houdaBn.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh70C6Yj9muY9kzMj4AtLvgbMroimuK1k',
    appId: '1:613181708633:ios:175de7fa6d8edd34cfd448',
    messagingSenderId: '613181708633',
    projectId: 'flutter-project-2aa41',
    storageBucket: 'flutter-project-2aa41.appspot.com',
    iosBundleId: 'come.houdaBn.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd5MOW1DJOJ0uNpVGqyy0waoa1jD6zgcA',
    appId: '1:613181708633:web:b7ea09183d37ff97cfd448',
    messagingSenderId: '613181708633',
    projectId: 'flutter-project-2aa41',
    authDomain: 'flutter-project-2aa41.firebaseapp.com',
    storageBucket: 'flutter-project-2aa41.appspot.com',
    measurementId: 'G-5R52SJCN1Z',
  );
}
